name: Maven Deploy
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        server-id: jboss-snapshots-repository
        settings-path: ${{ github.workspace }}
    - name: Deploy to GitHub Packages
      run: mvn deploy
      env:
        GITHUB_TOKEN: ${{ secrets.KIE_PARENT_TOKEN }}
